BTN_1 = "BTN_1"
BTN_2 = "BTN_2"
BTN_3 = "BTN_3"

MENU = "MENU"
INCOME = "INCOME"
METHOD = "METHOD"
EXPENSES = "EXPENSES"
DEPARTMENT = "DEPARTMENT"
CATEGORY = "CATEGORY"
AMOUNT = "AMOUNT"
OPERATIONS = "OPERATIONS"
TOTAL = "TOTAL"
FIRST = "FIRST"
SECOND = "SECOND"
SOURCE = "SOURCE"
REJECT = "REJECT"
CONFIRM = "CONFIRM"
FINAL = "FINAL"
UPDATE_EXPENSES = "UPDATE_EXPENSES"
UPDATE_INCOME = "UPDATE_INCOME"
BACK = "BACK"
STAT = "STAT"
GET_STAT = "GET_STAT"
BACK_TO_METHOD = 'BACK_TO_METHOD'
BACK_TO_PROJECT = 'BACK_TO_PROJECT'
BACK_TO_IN_PROJECT = 'BACK_TO_IN_PROJECT'
LOOK_INCOME = 'LOOK_INCOME'
LOOK_EXPENSES = 'LOOK_EXPENSES'

BUTTON_BACK_IN_PLACE = "IN_PLACE_BACK"

SECRET_LEVEL_BUTTON = "SCRT_LVL"
CONFIRM_DECLINE_BROADCAST = "CNFM_DCLN_BRDCST"
CONFIRM_BROADCAST = "CONFIRM"
DECLINE_BROADCAST = "DECLINE"
